### ISSUE TITLE
What should the POST request to the /auth/twitter/token route  contain?

### ISSUE THREAD

**Issue by Gzing** [drudge/passport-twitter-token#6]
I have been sending token, tokenSecret and userId but I get the undergiven error

{
    "errors": {
        "name": "InternalOAuthError",
        "message": "failed to fetch user profile",
        "oauthError": {
            "statusCode": 404,
            "data": "{\"errors\":[{\"message\":\"Sorry, that page does not exist\",\"code\":34}]}"
        }
    }
}

**Comment by stargt** [comment]
Very helpful. Thank you

**Comment by bhavyasanchaniya** [comment]
I have been sending 

oauth_token
oauth_token_secret
user_id

but i get the error.

{ InternalOAuthError: Failed to fetch user profile
    at /var/www/html/denode/node_modules/passport-twitter-token/lib/index.js:141:32
    at passBackControl (/var/www/html/hawker_node/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/var/www/html/hawker_node/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  name: 'InternalOAuthError',
  message: 'Failed to fetch user profile',
  oauthError:
   { statusCode: 401,
     data: '{"errors":[{"code":89,"message":"Invalid or expired token."}]}' } }
